# libcmidi

libcmidi is a MIDI event handling library for C. It is intended to be as compiler-agnostic as possible.

## Quick usage reference

1. Create a MIDI data container: +
`MIDI_t midi_in = { MIDIState_Status, { 0, 0, 0 } };`
1. Bind a MIDI event to your handler, which must be outlined as `void YourFunctionName( MIDI_t* midi )`: +
`MIDI_SetStatusHandler( MIDI_CV_NOTE_ON, YourFunctionName );`
1. Every time you receive a _single_ byte on the MIDI interface, pass it through the `MIDI_Task(...)` function: +
`MIDI_Task( rxData, &midi );`

When a complete MIDI message is received, `libcmidi` will pick out the right function handler for you, as long as it has been defined and bound to a MIDI message. See the MIDI specification and `midi.h` to see which MIDI events are available.

### Quick usage example

Below is a quick usage example that
* Creates a MIDI event container called `midi_in`
* Declares/Defines an event handler called `void NoteOnTest(...)
* Binds the event handler to a MIDI event code
* Simulates a Note On event to trigger the event handler

----
#include "midi.h"
#include <stdio.h>

// Create the container
MIDI_t midi_in = { MIDIState_Status, { 0, 0, 0 } };


// Define/Declare the event handler
void NoteOnTest(MIDI_t* midi) {
	printf("MIDI_CV_NOTE_ON PASS");
}

int main( void ) {
	// Bind the event handler to the MIDI event code
	MIDI_SetStatusHandler( MIDI_CV_NOTE_ON, NoteOnTest );

	// Simulate a Note On event
	MIDI_Task(MIDI_CV_NOTE_ON, &midi_in);
	MIDI_Task(0x40, &midi_in);
	MIDI_Task(0x40, &midi_in);

	return 0;
}
----